version: '3'

services:
  pastebin:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    command: python main.py
    volumes:
      - ./:/opt/project
    links:
      - redis

  redis:
    image: redis:3.2
    ports:
      - "6377:6379"