version: '3.4'

services:
  pastebin:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
      network: host
    command: python main.py
    volumes:
      - ./:/opt/project
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6377:6379"
